BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "balena-imx8mplus"
BBFILE_PATTERN_balena-imx8mplus := "^${LAYERDIR}/"
BBFILE_PRIORITY_balena-imx8mplus = "1337"
LAYERSERIES_COMPAT_balena-imx8mplus = "kirkstone scarthgap"
LAYERSERIES_COMPAT_meta-imx8mp-isp-imx219 = "kirkstone scarthgap"

BBMASK += "meta-bsp-imx8mp/recipes-nxp-demo-experience/nxp-demo-experience"
BBMASK += "meta-compulab-bsp/meta-bsp/recipes-bsp/base-files"
BBMASK += "meta-compulab-bsp/meta-bsp/recipes-bsp/coremark"
BBMASK += "meta-compulab-bsp/meta-bsp/recipes-bsp/systemd"
BBMASK += "meta-compulab-bsp/meta-bsp/recipes-bsp/wpa-supplicant"
BBMASK += "meta-compulab-bsp/meta-bsp/recipes-bsp/u-boot-ai-script"
BBMASK += "meta-compulab-bsp/meta-bsp/recipes-bsp/u-boot-scr"
BBMASK += "meta-compulab-bsp/meta-bsp/recipes-bsp/u-boot-update-scr"

# Masked because it disables the `tr` command in initramfs,
# causing the data partition to not be expanded.
BBMASK += "meta-bsp-imx8mp/recipes-core/busybox"
KERNEL_IMAGETYPE:compulab-mx8mp = "Image.gz"
KERNEL_PACKAGE_NAME="kernel"

KERNEL_DEVICETREE:iot-gate-imx8plus += " \
       compulab/iot-gate-imx8plus.dtb \
       compulab/iot-gate-imx8plus-usbdev.dtb \
       compulab/iot-gate-imx8plus-m2tpm.dtb \
       compulab/iot-gate-imx8plus-m7.dtb \
       compulab/iot-gate-imx8plus-mdpcb-m2tpm.dtb \
"

# Mask meta-balena-hab recipes for other SOM families
BBMASK += "meta-balena-hab/recipes-bsp/u-boot/u-boot-variscite.bbappend"
BBMASK += "meta-balena-hab/recipes-kernel/linux/linux-variscite_%.bbappend"

DRAM_CONF:iotdin-imx8p="d2d4"
DRAM_CONF:iotdin-imx8p-d1d8="d1d8"

DRAM_CONF:iot-gate-imx8plus="d2d4"
DRAM_CONF:iot-gate-imx8plus-d1d8="d1d8"

HOSTTOOLS:remove = " git-lfs "
HOSTTOOLS:remove = " bison "
MACHINE_FEATURES:remove = "optee-os"
MACHINE_FEATURES:remove = "efi"

# Auto-load imx_rpmsg_tty module at boot for M7 RPMsg communication
IMAGE_INSTALL:append:iot-gate-imx8plus = " imx-rpmsg-tty-autoload"
